### ISSUE TITLE
Title field: Zeri records

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#155]
The title field of the Zeri artworks records now is composed as <name of artist>,<subject>. That should change.

The value for the title field should be what in the Zeri's database is under the field "SGTT". If that field is empty, the content to include is that of field "SGTI"

**Comment by mafragias** [comment]
this is fixed in mappings it will be updated with the new data import!

**Comment by MinadakisNikos** [comment]
@mafragias https://dev.artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fzeri%2Fwork%2F26370 still see it. what happened?
